<?php
    $customer       = $this->getCustomer();
    $helper         = $this->helper('conturifurnizori');
    $someVariable   = false;
?>

<div class="my-account">
    <div class="dashboard setari">
        <div class="page-title">
            <h1><?php echo $this->__('Rapoarte avansate') ?></h1>
        </div>
        
        <div class="box-account box-info">
            <div class="box">
                <div class="box-head">
                    <h2><?php echo $this->__('Section title') ?><span class="view-more"><?php echo $this->__('learn more') ?></span></h2>
                </div>
                <div class="box-content">
                    <?php if ($someVariable): ?>
                        
                    <?php else: ?>
                        <p><?php echo $this->__('No content...'); ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
            
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function(){
        
        jQuery('.view-more').click(function(){
            jQuery(this).closest('.box').find('.some-class').toggleClass('active');
            if (jQuery(this).text() == 'learn more') {
                jQuery(this).text('hide');
            } else {
                jQuery(this).text('learn more');
            }
            
        });
        
    })
</script>

