<?php
    $_helper = $this->helper('conturifurnizori');
    $_productCollection = $this->getConturiCollection();
    $accountDetails = $_helper->getAttributesFromGroup(25); // 25 is for "Detalii Cont"
?>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('conturifurnizori')->toHtml() ?>

<?php if (!$_productCollection->getSize()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = 4 ?>
        <?php $lineCount = 0 ?>
        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
             <li class="item first">
                 <div class="product-info">
                     <h2 class="product-name heading">
                         <?php echo $this->__('Configurare Cont') ?>
                     </h2>
                     <ul class="account-attributes heading">
                         <?php foreach ($accountDetails as $_detail): ?>
                             <?php if ($_detail->getIsVisibleOnFront()): ?>
                                 <li class="heading<?php echo $lineCount%2 ? ' odd' : ' even' ?>"><?php echo $_detail->getFrontendLabel(); ?></li>
                             <?php $lineCount++; ?>
                             <?php  endif;?>
                         <?php endforeach ?>
                     </ul>
                 </div>
             </li>
             <?php $i = 1; foreach ($_productCollection as $_product): ?>
             <?php //Zend_Debug::dump(get_class_methods($_product)); die(); ?>
             <li class="item<?php if($i%$_columnCount == 0): ?> first<?php elseif($i+1 == $_columnCount): ?> last<?php endif; ?>">
                 <div class="product-info">
                     <?php // Zend_Debug::dump($_product->getData()); ?>
                     <h2 class="product-name">
                         <?php echo $this->stripTags($_product->getName(), null, true) ?>
                     </h2>
                     <ul class="account-attributes">
                         <?php $lineCount = 0 ?>
                         <?php foreach ($accountDetails as $_detail): ?>
                             <?php //Zend_Debug::dump($_detail->getData()) ?>
                             <?php if ($_detail->getIsVisibleOnFront()): ?>
                                 <li class="<?php echo $_detail->getFrontendInput() == 'boolean' ? 'symbol' : '' ?> <?php echo $lineCount%2 ? 'odd' : 'even' ?>">
                                     <?php echo $_helper->getFormatedAttributeValue($_detail->getAttributeCode(), $_product);  ?>
                                 </li>
                                <?php $lineCount++; ?>
                             <?php endif; ?>
                         <?php endforeach ?>
                         
                         <?php if ($_product->getContTip() == 'gratuit'): ?>
                             
                             <li class="account-type"><?php echo $_product->getContTip() ?></li>
                             <li class="actions">
                                 <button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" title="<?php echo $this->__('Creaza ') . $_product->getName() ?>" type="submit">
                                     <span><span><?php echo $this->__('Creaza ') . $_product->getName() ?></span></span>
                                 </button>
                             </li>
                             <li class="more-details"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Mai multe detalii') ?></a></li> 
                             
                         <?php elseif ($_product->getContTip() == 'platit'): ?>
                             
                             <?php if ($_product->getTypeInstance(true)->hasOptions($_product)): ?>
                                 <li class="starting-price">
                                     <?php echo $this->__('De la ') ?><br />
                                     <?php echo Mage::helper('core')->currency(min($this->getPriceAverage($_product)), true, false); ?>
                                     <?php echo $this->__(' / luna ') ?>
                                 </li>
                             <?php else: ?>
                                 <li class="price">
                                     <?php echo Mage::helper('core')->currency($_product->getFinalPrice(), true, false); ?>
                                     <?php echo $this->__(' / luna ') ?>
                                 </li>
                             <?php endif ?>
                             <li class="actions">
                                 <button class="button" onclick="setLocation('<?php echo $this->getBaseUrl() . $_product->getUrlPath() ?>')" title="<?php echo $this->__('Comanda ') . $_product->getName() ?>" type="submit">
                                     <span><span><?php echo $this->__('Comanda ') . $_product->getName() ?></span></span>
                                 </button>
                             </li>
                             <li class="more-details"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Mai multe detalii') ?></a></li> 
                             
                         <?php endif; ?>
                         
                     </ul>
                 </div>
             </li>
             <?php $i++; endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<script type="text/javascript">
    function addToCart(url)
    {
        
    }
</script>
