
<?php

    if (Mage::app()->getRequest()->getActionName() == 'provider') {
        // Picode_MiniAdvancedSearch_Block_Results
        $_providersCollection = $this->getQuickSearchResult();
    } else {
        // Picode_ConturiFurnizori_Block_Conturi_Providers
        $_providersCollection = $this->getLoadedProductCollection();
    }

    $_helper = $this->helper('conturifurnizori');
    //echo $_providersCollection->getSelect();
?>
<div class="page-title">
    <h1><?php echo $this->getLayout()->getBlock('head')->getTitle() ?></h1>
</div>

<?php if (Mage::app()->getRequest()->getActionName() != 'provider'): ?>
    <div class="regions-holder">
        <?php
        //$regionCollection = $_helper->getRegionCollection('RO');
        //Zend_Debug::dump($regionCollection);
        $regionCollection = Mage::getModel('directory/region')->getResourceCollection()
            ->addCountryFilter('RO')
            ->load();
        ?>
        <h3><?php echo $this->__('Sunt afișați furnizorii din') ?></h3>
        <select id="region-select" class="regions-options">
            <option value=""><?php echo $this->__('Toate județele') ?></option>
            <?php foreach ($regionCollection as $region): ?>
                <?php $regionName = strtolower(str_replace(' ', '-', $region->getDefaultName())) ?>
                <?php $regionFromUrl = Mage::app()->getRequest()->getParam('judet'); ?>
                <?php $currentUrl = explode('?', Mage::helper('core/url')->getCurrentUrl()); ?>

                <option value="<?php echo $currentUrl[0] ?>?judet=<?php echo $region->getRegionId(); ?>" <?php echo $regionFromUrl == $region->getRegionId() ? 'selected="selected"' : ''; ?>>
                    <?php echo $region->getDefaultName(); ?>
                </option>
            <?php endforeach; ?>
        </select>
        <script type="text/javascript">
            jQuery(document).ready(function () {
                jQuery('#region-select').change(function () {
                    if (jQuery(this).val() != '') {
                        location.href = jQuery(this).val();
                    } else {
                        location.href = '<?php echo $currentUrl[0] ?>';
                    }
                });
            });
        </script>
    </div>
<?php endif; ?>

<?php if (!$_providersCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('Momentan nu avem niciun furnizor de listat.') ?></p>
<?php else: ?>
    <div class="providers">
        <?php echo $this->getToolbarHtml() ?>

        <?php $_collectionSize = $_providersCollection->count() ?>
        <?php $_columnCount = 2; ?>

        <ul class="products-list products-grid--max-<?php echo $_columnCount; ?>-col">
            <?php $_iterator = 0; ?>
            <?php foreach ($_providersCollection as $_provider): ?>
                <?php //Zend_Debug::dump($_provider->getData()); ?>
                <?php //$_provider = Mage::getModel('customer/customer')->load($_provider->getId()); ?>
                <li class="item<?php if ($_iterator == 0): ?> first<?php endif; ?><?php if (++$_iterator == sizeof($_providersCollection)): ?> last<?php endif; ?>">
                    <div class="left-inside">
                        <a href="<?php echo $this->getBaseUrl() . 'conturifurnizori/furnizori/profil/' . $_helper->seoFriendlyUrl($_provider->getBusinessDescriptionsTitle()) . '/' . $_provider->getId() ?>" title="<?php echo $_provider->getBusinessDescriptionsTitle() ?>" class="provider-image">
                            <?php /* if ($_provider->getFurnizorAccountLevel() == '2'): ?>
                                <div class="ribbon-wrapper">
                                    <div class="ribbon">
                                        <p><?php echo $this->__('Furnizor<br />PREMIUM'); ?></p>

                                    </div>
                                </div>
                            <?php endif; */ ?>
                            <?php //if ($_provider->getBusinessImagesLogo()): ?>
                                <?php $img = $_provider->getBusinessImagesLogo() ? $_helper->resizeImage($_provider->getBusinessImagesLogo(), 250, false, true) : $this->getBaseUrl() .
                                    'media/catalog/product/placeholder/default/logo-placeholder.jpg'; ?>
                                <img id="product-collection-image-<?php echo $_provider->getId(); ?>"
                                     src="<?php echo $img ?>"
                                     alt="<?php echo $_provider->getBusinessDescriptionsTitle() ?>"
                                    />
                            <?php //endif; ?>
                        </a>
                        <div class="reputation-wrapper">
                            <div class="popularity-views">
                                <label><?php echo $this->__('Reputație') ?></label>
                                <label><?php echo $this->__('Afişări') ?></label>
                                <span id="provider-reputation" class="value earned-points">
                                    <?php //echo $_provider->getProviderReputation() ? $_provider->getProviderReputation() : 0 ?>
                                    <?php $decimals = $_provider->getProviderReputation() > 999 ? 2 : 0; ?>
                                    <?php $reputationPoints = $_provider->getProviderReputation() ? $_helper->convertReputationPoints($_provider->getProviderReputation(), $decimals) : '0'; ?>
                                    <?php echo $reputationPoints ?>
                                </span>
                                <span id="provider-views" class="value">
                                    <?php echo $_provider->getProviderViews() ? $_provider->getProviderViews() : 0 ?>
                                </span>
                            </div>    
                        </div>
                    </div>
                    <div class="right-inside">
                        <a class="m-provider-title provider-title"
                           href="<?php echo $this->getBaseUrl() . 'conturifurnizori/furnizori/profil/' . $_helper->seoFriendlyUrl($_provider->getBusinessDescriptionsTitle()) . '/' . $_provider->getId() ?>"
                           title="<?php echo $_provider->getBusinessDescriptionsTitle() ?>">
                            <h3><?php echo $_provider->getBusinessDescriptionsTitle() ?></h3>
                        </a>
                        <div class="provider-info-top">
                            <h2 class="product-name">
                                <a href="<?php echo $this->getBaseUrl() . 'conturifurnizori/furnizori/profil/' . $_helper->seoFriendlyUrl($_provider->getBusinessDescriptionsTitle()) . '/' . $_provider->getId() ?>"
                                   title="<?php echo $_provider->getBusinessDescriptionsTitle() ?>" class="provider-title">
                                    <?php echo $_provider->getBusinessDescriptionsTitle() ?>
                                    <?php echo $this->__(' / ') ?>
                                    <span><?php echo $_provider->getFurnizorLocationCity() ?></span>
                                </a>
                            </h2>
                            
                            <div class="attr-servicii">
                                <label>Oferă servicii:</label>
                                <?php echo strtoupper($_provider->getResource()->getAttribute('furnizor_company_services')->getFrontend()->getValue($_provider)); ?>
                                <?php if ($_provider->getData('furnizor_company_zone') != ''): ?>
                                    <label><?php echo $this->__('în') ?></label>
                                    <?php if ($_provider->getFurnizorCompanyZone() == 5): ?>
                                        <?php $personalizedZones = $_provider->getFurnizorCompanyCstzone() ?>
                                        <?php $personalizedZonesArr = explode(',', $personalizedZones) ?>
                                        <?php foreach ($personalizedZonesArr as $key => $val): ?>
                                            <?php $region = Mage::getModel('directory/region')->load($val) ?>
                                            <?php echo trim($region->getDefaultName()); ?>
                                            <?php if ($key < count($personalizedZonesArr) - 1): ?>
                                                <?php echo $this->__(','); ?>
                                            <?php else: ?>
                                                <?php //echo $this->__('și altele...'); ?>
                                                <?php //break; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php elseif ($_provider->getFurnizorCompanyZone() == 1): ?>
                                        <?php echo $_provider->getResource()->getAttribute('furnizor_location_city')->getFrontend()->getValue($_provider); ?>
                                    <?php elseif ($_provider->getFurnizorCompanyZone() == 2): ?>
                                        <?php echo $_provider->getResource()->getAttribute('furnizor_location_province')->getFrontend()->getValue($_provider); ?>
                                    <?php elseif ($_provider->getFurnizorCompanyZone() == 3): ?>
                                        <?php echo $_provider->getResource()->getAttribute('furnizor_company_zone')->getFrontend()->getValue($_provider); ?>
                                        <?php echo $_provider->getResource()->getAttribute('furnizor_location_province')->getFrontend()->getValue($_provider) . 'ului'; ?>
                                    <?php else: ?>
                                        <?php echo $_provider->getResource()->getAttribute('furnizor_company_zone')->getFrontend()->getValue($_provider); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <div class="activity-description">
                                <div class="description">
                                    <?php echo $this->truncate($_provider->getBusinessDescriptionsDesc(), 260); ?>
                                </div>
                                <a href="<?php echo $this->getBaseUrl() . 'conturifurnizori/furnizori/profil/' . $_helper->seoFriendlyUrl($_provider->getBusinessDescriptionsTitle()) . '/' . $_provider->getId() ?>" class="read-more">
                                   <span class="ion-ios-arrow-right"></span>
                               </a>
                            </div>
                        </div>
                        <div class="provider-info-bottom">
                            <div class="bottom-left">
                                <span class="attr-info">
                                    <label>Oferte active:</label>
                                    <?php $offersCount = $_helper->countActiveOffers($_provider->getId()); ?>
                                    <?php if ($offersCount): ?>
                                        <?php echo $offersCount; ?>
                                    <?php else: ?>
                                        <?php echo $this->__('Nicio ofertă activă'); ?>
                                    <?php endif; ?>
                                </span>
    
                                <span class="attr-info">
                                    <label>Preț mediu:</label>
                                    <?php if ($offersCount): ?>
                                        <?php $price = round($_helper->getPriceAvarange($_provider->getId())); ?>
                                        <?php echo Mage::helper('core')->currency($price, true, false); ?>
                                    <?php else: ?>
                                        <?php echo $this->__('-') ?>
                                    <?php endif; ?>
                                </span>
                                <span class="attr-info">
                                    <label>Experiență:</label>
                                    <?php echo $_provider->getResource()->getAttribute('business_descriptions_exp')->getFrontend()->getValue($_provider); ?>
                                </span>
                            </div>
                       </div>
                </div>
                </li>
            <?php endforeach; ?>
        </ul>

        <?php echo $this->getToolbarHtml() ?>
    </div>
<?php endif; ?>

<?php /*
<span class="attr-info slogan">
    <?php if ($_provider->getBusinessDescriptionsSlogan()): ?>
        <?php echo $this->truncate($_provider->getBusinessDescriptionsSlogan(), 85); ?>
    <?php else: ?>
        <?php echo $this->truncate($_provider->getBusinessDescriptionsDesc(), 85); ?>
    <?php endif; ?>
</span>
*/ ?>