<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('Old Portofoliu') ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <li>
                <strong><?php echo $this->__('Albume foto') ?></strong>
                <ul>
                    <li>Album 1</li>
                    <li>Album 2</li>
                </ul>
            </li>
            
            <li class="last">
                <strong><?php echo $this->__('Videoclipuri') ?></strong>
                <ul>
                    <li>Video 1</li>
                    <li>Video 2</li>
                </ul>
            </li>
        </ul>
    </div>
</div>
