<?php
    $furnizoriHelper = $this->helper('conturifurnizori');
    $messages = $this->getUnreadMessages();
?>

<div class="box-content">
    <div class="table">
        <div class="table-head">
            <div class="head-row">
                <div class="table-data msg-subject">
                    <?php echo $this->__('Subiect') ?>
                </div>
                <div class="table-data msg-from">
                    <?php echo $this->__('Expeditor') ?>
                </div>
                <div class="table-data msg-date">
                    <?php echo $this->__('Data') ?>
                </div>
                <div class="table-data msg-msg">
                    <?php echo $this->__('Mesaj') ?>
                </div>
                <div class="table-data msg-action">
                    <?php echo $this->__('') ?>
                </div>
            </div>
        </div>
        <div class="table-content">
            <?php if (!$messages->getSize()): ?>
                <div class="table-row">
                    <div class="table-data no-message">
                        <?php echo $this->__('Nu ai niciun mesaj necitit.'); ?>
                        <a href="<?php echo $this->getUrl('conturifurnizori/mesaje/casutapostala/',array('_secure'=>true)) ?>">
                            <?php echo $this->__(' Vezi toate mesajele') ?>
                            <span class="ion-ios-arrow-right"></span>
                        </a>
                    </div>
                </div>
            <?php else: ?>
                <?php foreach ($messages as $message): ?>
                    <div class="table-row">
                        <div class="table-data msg-subject">
                            <a href="<?php echo $this->getReadAction($message->getId()); ?>" title="<?php echo $this->__('Citeste mesajul') ?>">
                                <?php echo $furnizoriHelper->stringTruncate($message->getSubject(), 30); ?>
                            </a>
                        </div>
                        <div class="table-data msg-from">
                            <?php echo $this->getSenderFullName($message->getSenderId(), $message->getReplayTo()) ?>
                        </div>
                        
                        <div class="table-data msg-date">
                            <?php echo date('d.m.Y', strtotime($message->getCreatedTime())); ?>
                        </div>
                        <div class="table-data msg-msg">
                            <?php echo $furnizoriHelper->stringTruncate($message->getMessage(), 70); ?>
                        </div>
                        <div class="table-data msg-action">
                            <a href="<?php echo $this->getReadAction($message->getId()); ?>" title="<?php echo $this->__('Citeste mesajul') ?>"><?php echo $this->__('Citeste') ?></a>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</div>

