<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $_provider = Mage::getModel('customer/customer')->load($_product->getOfgCustomerId());
	$productType = $_product->getOfgTipOferta();
    //Zend_Debug::dump($productType);
?>

<div class="tabbed-area">
    <div class="tabs-wrapper">
        <ul class="tabs" <?php //echo $productType != 48 ? 'style="max-width: 845px;"' : ''; ?>>
            <li class="tab-title">
                <span id="tab-generale" class="active"><?php echo $this->__('Informatii generale') ?></span>
            </li>
            <?php if ($productType == 1 || $productType == 3): ?>
	            <li class="tab-title">
	                <span id="tab-foto" class=""><?php echo $this->__('Detalii foto') ?></span>
	            </li>
            <?php endif; ?>
            <?php if ($productType == 2 || $productType == 3): ?>
	            <li class="tab-title">
	                <span id="tab-video" class=""><?php echo $this->__('Detalii video') ?></span>
	            </li>
	        <?php endif; ?>
            <li class="tab-title">
                <span id="tab-contact"><?php echo $this->__('Detalii contact') ?></span>
            </li>
            <?php /*
            <li class="tab-title">
                <span id="tab-opinii"><?php echo $this->__('Opinii clienti') ?></span>
            </li>
            */ ?>
        </ul>
    </div>

    <div class="contents">
        <?php /*
        <div id="content-generale" class="content active">
            <h2><?php echo $this->__('Informații generale') ?></h2>
            <?php $productAttributes = $this->getProductAttributesBySet($_product, 25, 190); ?>
            <div class="col-2 left">
            	<?php $i = 0; foreach ($productAttributes as $attribute): ?>
            		<div class="attribute-row <?php echo $i%2 == 0 ? 'even' : 'odd'; ?>">
	                    <label class="attr-title"><?php echo $attribute['title'] ?></label>
	                    <span class="attr-value"><?php echo $attribute['value']; ?></span>
	                </div>
	        <?php if ($i == floor(count($productAttributes) / 2)): ?>
            	</div>
            	<div class="col-2 right">
	        <?php endif; ?>
	            <?php $i++; endforeach; ?>
            </div>
        </div>
        */ ?>
        <div id="content-generale" class="content active">
            <div class="col-2 left">
                <h2><?php echo $this->__('Informații generale') ?></h2>
                <div class="attribute-row even">
                    <label class="attr-title"><?php echo $this->__('Denumire furnizor') ?></label>
                    <span class="attr-value"><?php echo $_product->getOfgCustomerFrontname(); ?></span>
                </div>
                <div class="attribute-row odd">
                    <label class="attr-title"><?php echo $this->__('Tip ofertă') ?></label>
                    <span class="attr-value"><?php echo $_product->getResource()->getAttribute('ofg_tip_oferta')->getFrontend()->getValue($_product); ?></span>
                </div>
                <div class="attribute-row even">
                    <?php
                        $zoneArr = explode(',', $_product->getData('ofg_zona_personalizata'));
                        foreach ($zoneArr as $zone) {
                            $zoneText[] = Mage::getModel('directory/region')->load($zone)->getName();
                        }
                        $attributeText = implode(', ', $zoneText);
                    ?>
                    <label class="attr-title"><?php echo $this->__('Valabilă pentru:') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <?php if ($_product->getOfgNrFotografi()): ?>
	                <div class="attribute-row odd">
	                    <label class="attr-title"><?php echo $this->__('Fotografi') ?></label>
	                    <span class="attr-value"><?php echo $_product->getOfgNrFotografi(); ?></span>
	                </div>
	            <?php endif; ?>
                <?php if ($_product->getOfgNrCameramani()): ?>
	                <div class="attribute-row even">
	                    <label class="attr-title"><?php echo $this->__('Cameramani') ?></label>
	                    <span class="attr-value"><?php echo $_product->getOfgNrCameramani(); ?></span>
	                </div>
                <?php endif; ?>
                <div class="attribute-row odd">
                    <label class="attr-title"><?php echo $this->__('Cheltuieli transport') ?></label>
                    <span class="attr-value"><?php echo $_product->getResource()->getAttribute('ofg_cheltuieli_transport')->getFrontend()->getValue($_product); ?></span>
                </div>
                <div class="attribute-row even">
                    <label class="attr-title"><?php echo $this->__('Cheltuieli cazare') ?></label>
                    <span class="attr-value"><?php echo $_product->getResource()->getAttribute('ofg_cheltuieli_cazare')->getFrontend()->getValue($_product); ?></span>
                </div>
            </div>
            <div class="col-2 right">
                <h2><?php echo $this->__('Prezenta echipei') ?></h2>
                <div class="attribute-row even">
                    <label class="attr-title"><?php echo $this->__('Timp alocat evenimentului') ?></label>
                    <span class="attr-value"><?php echo $_product->getResource()->getAttribute('ofg_disponibilitate')->getFrontend()->getValue($_product); ?></span>
                </div>
                <div class="attribute-row odd">
                    <?php $attributeText = $_product->getData('ofg_pregatiri_nunta') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Pregătiri nuntă') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row even">
                    <?php $attributeText = $_product->getData('ofg_cununie_civila') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Cununie civilă') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row odd">
                    <?php $attributeText = $_product->getData($_product->getOfgCununieCivilaAltaZi()) ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Cununie civilă în altă zi?') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row even">
                    <?php $attributeText = $_product->getData('ofg_cununie_religioasa') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Cununie religioasă') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row odd">
                    <?php $attributeText = $_product->getData('ofg_restaurant') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Restaurant / Petrecere') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row even">
                    <?php $attributeText = $_product->getData('ofg_restaurant_panala') == 'alt-moment' ? $_product->getResource()->getAttribute('ofg_restaurant_definit')->getFrontend()->getValue($_product) : $_product->getResource()->getAttribute('ofg_restaurant_panala')->getFrontend()->getValue($_product); ?>
                    <label class="attr-title"><?php echo $this->__('Prezența la restaurant (până la)') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
            </div>
            <div class="row-separator"></div>
            <div class="col-2 left">
                <h2><?php echo $this->__('Sedinte ' . $_product->getResource()->getAttribute('ofg_tip_oferta')->getFrontend()->getValue($_product) . ' programate') ?></h2>
                <div class="attribute-row even">
                    <label class="attr-title"><?php echo $this->__('Nr. maxim ședințe programate') ?></label>
                    <span class="attr-value"><?php echo $_product->getResource()->getAttribute('ofg_nr_sedinte')->getFrontend()->getValue($_product); ?></span>
                </div>
                <div class="attribute-row odd">
                    <?php $attributeText = $_product->getData('ofg_sedinta_logodna') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Ședintă logodnă (înainte de nuntă)') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row even">
                    <?php $attributeText = $_product->getData('ofg_sedinte_inainte_biserica') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Ședință înainte de biserică') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
            </div>
            <div class="col-2 right">
                <h2 class="empty">&nbsp;</h2>
                <div class="attribute-row even">
                    <?php $attributeText = $_product->getData('ofg_sedinte_dupa_biserica') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('Ședință după biserică') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <?php $attributeText = $_product->getOfgSedinteSuplimentara() ? $_product->getOfgSedinteSuplimentara() : 'Nu'; ?>
                <div class="attribute-row odd">
                    <label class="attr-title"><?php echo $this->__('Alte sedinte programate') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
                <div class="attribute-row even">
                    <?php $attributeText = $_product->getData('ofg_trash_the_dress') ? 'Da' : 'Nu'; ?>
                    <label class="attr-title"><?php echo $this->__('"Trash the Dress" (după nuntă)') ?></label>
                    <span class="attr-value"><?php echo $attributeText; ?></span>
                </div>
            </div>
        </div>

        <?php if ($productType == 1 || $productType == 3): ?>
	        <div id="content-foto" class="content">
	            <h2><?php echo $this->__('Detalii foto') ?></h2>
	            <?php $productAttributes = $this->getProductAttributesBySet($_product, 25, 181); ?>
	            <div class="col-2 left">
	            	<?php $i = 0; foreach ($productAttributes as $attribute): ?>
	            		<div class="attribute-row <?php echo $i%2 == 0 ? 'even' : 'odd'; ?>">
		                    <label class="attr-title"><?php echo $attribute['title'] ?></label>
		                    <span class="attr-value"><?php echo $attribute['value']; ?></span>
		                </div>
		            <?php $i++; endforeach; ?>
	            </div>
	            <div class="col-2 right">
		           	<?php if ($_product->getOffSlideShow()): ?>
		            	<div class="attribute-row single-attr">
			            	<span class="attr-title even"><?php echo $this->__('Descriere Slideshow') ?></span>
			            	<span class="attr-value odd"><?php echo $_product->getOffSlideShowDetalii() ?></span>
			            </div>
			        <?php endif; ?>

		            <?php if ($_product->getOffAlbumClasic()): ?>
		            	<div class="attribute-row single-attr">
			            	<span class="attr-title even"><?php echo $this->__('Descriere Album Clasic') ?></span>
			            	<span class="attr-value odd"><?php echo $_product->getOffAlbumClasicDetalii() ?></span>
			            </div>
		            <?php endif; ?>

	            	<?php if ($_product->getOffAlbumCarte()): ?>
	            		<div class="attribute-row single-attr">
			            	<span class="attr-title even"><?php echo $this->__('Descriere Album FotoCarte') ?></span>
			            	<span class="attr-value odd"><?php echo $_product->getOffAlbumCarteDetalii() ?></span>
			            </div>
		            <?php endif; ?>
	            </div>
	        </div>
	    <?php endif; ?>

	    <?php if ($productType == 2 || $productType == 3): ?>
	        <div id="content-video" class="content">
	            <h2><?php echo $this->__('Detalii video') ?></h2>
	            <?php $productAttributes = $this->getProductAttributesBySet($_product, 25, 180); ?>
	            <div class="col-2 left">
	            	<?php $i = 0; foreach ($productAttributes as $attribute): ?>
	            		<div class="attribute-row <?php echo $i%2 == 0 ? 'even' : 'odd'; ?>">
		                    <label class="attr-title"><?php echo $attribute['title'] ?></label>
		                    <span class="attr-value"><?php echo $attribute['value']; ?></span>
		                </div>
		        <?php if ($i == floor(count($productAttributes) / 2)): ?>
	            	</div>
	            	<div class="col-2 right">
		        <?php endif; ?>
		            <?php $i++; endforeach; ?>
	            </div>

	            <?php if ($_product->getOfvDetaliiSuplimentare()): ?>
		    		<div class="attribute-row single-attr">
		            	<span class="attr-title even"><?php echo $this->__('Detalii suplimentare') ?></span>
		            	<span class="attr-value odd"><?php echo $_product->getOfvDetaliiSuplimentare() ?></span>
		            </div>
		        <?php endif; ?>
	        </div>
	    <?php endif; ?>

        <div id="content-contact" class="content">
            <h2><?php echo $this->__('Detalii contact') ?></h2>
            <?php $contactDetails = $this->getProviderAttributesBySet($_provider, 'furnizor_contact'); ?>
            <div class="col-2 left">
            	<?php $i = 0; foreach ($contactDetails as $contact): ?>
            		<div class="attribute-row <?php echo $i%2 == 0 ? 'even' : 'odd'; ?>">
            			<?php if (trim(strtolower($contact['title'])) == 'email'): ?>
		                    <label class="attr-title"><?php echo $contact['title'] ?></label>
		                    <span class="attr-value">
		                    	<?php
				    		    	$emailArr = explode('@', $contact['value']);
									$domainArr = explode('.', $emailArr[1]);
									$unicKey = $this->helper('conturifurnizori')->generateUnicKey();
								?>
				    			<script type="text/javascript">
				    			//<![CDATA[
				    				rebuildAddress('<?php echo $emailArr[0]; ?>', '<?php echo $domainArr[0]; ?>', '<?php echo $domainArr[1]; ?>');
				    				function rebuildAddress(name, domain, ext)
									{
										document.write(name + '<span class="hidden-space"><?php echo $unicKey ?></span><span class="ion-at at"></span><span class="hidden-space"><?php echo $unicKey ?></span>' + domain + '<span class="hidden-space"><?php echo $unicKey ?></span>.' + ext);
									}
				    			//]]>
				    			</script>
		                    </span>
		                <?php else: ?>
		                	<label class="attr-title"><?php echo $contact['title'] ?></label>
		                    <span class="attr-value"><?php echo $contact['value']; ?></span>
		                <?php endif; ?>
	                </div>
	            <?php $i++; endforeach; ?>
            </div>
            <?php $contactDetails = $this->getProviderAttributesBySet($_provider, 'business_networks'); ?>
            <div class="col-2 right">
            	<?php $i = 0; foreach ($contactDetails as $contact): ?>
            		<div class="attribute-row <?php echo $i%2 == 0 ? 'even' : 'odd'; ?>">
            			<label class="attr-title"><?php echo $contact['title'] ?></label>
                            <?php if (trim(strtolower($contact['title'])) == 'id skype' || trim(strtolower($contact['title'])) == 'id yahoo messenger'): ?>
                                <span class="attr-value"><?php echo $contact['value']; ?></span>
                            <?php else: ?>
                                <?php
                                    $link = strpos($contact['value'], 'http://') !== false || strpos($contact['value'], 'https://') !== false ? $contact['value'] : 'https://' . $contact['value'];
                                ?>
                                <span class="attr-value">
                                    <a class="contact-link" href="<?php echo $link ?>" title="" target="_blank"><?php echo $link ?></a>
                                </span>
                            <?php endif; ?>
	                </div>
	            <?php $i++; endforeach; ?>
            </div>
        </div>
        <?php /*
        <div id="content-opinii" class="content">
            <div class="customer-reviews">
                <?php //echo $this->getChildHtml('reviews') ?>
                <?php echo $this->getChildHtml('product_review'); ?>
            </div>
            <div class="review-form">
                <?php //echo $this->getChildHtml('product_additional_data_review') ?>
                <?php echo $this->getChildHtml('review_form') ?>
                <?php //echo $this->getChildHtml('product_review'); ?>
            </div>
        </div>
        */ ?>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    jQuery('.tab-title span').click(function(){
        // remove active class from all other elements
        jQuery('.tab-title span, .contents .content').removeClass('active');
        // add active class to clicked element
        var clickedId = jQuery(this).attr('id').split('-');
        jQuery(this).addClass('active');
        jQuery('#content-' + clickedId[1]).addClass('active');
    });

//]]>
</script>