<div class="top-content">
    <div class="content-heading">
        <h1>Servicii foto video</h1>
        <p>fotografi şi cameramani pentru nunta</p>
    </div>
    <div class="content-middle">
        <div class="middle-2-cols">
            <div class="col-left">
                <img src="<?php echo $this->getBaseUrl() ?>media/wysiwyg/homebox-wedding.jpg" />
                <div>
                    <h2>Pentru miri</h3>
                    <p>Lorem ipsum dolor sit amet</p>
                    <ul>
                        <li>Quo id porro vivendo voluptatibus</li>
                        <li>Cum platonem molestiae reprehendunt</li>
                        <li>Ea eam oblique fabulas, ei velit detraxit</li>
                    </ul>
                    <a class="button" href="">Cont nou</a>
                </div>
            </div>
            <div class="col-right">
                <img src="<?php echo $this->getBaseUrl() ?>media/wysiwyg/homebox-providers.jpg" />
                <div>
                    <h2>Pentru furnizori</h3>
                    <p>Lorem ipsum dolor sit amet</p>
                    <ul>
                        <li>Quo id porro vivendo voluptatibus</li>
                        <li>Cum platonem molestiae reprehendunt</li>
                        <li>Ea eam oblique fabulas, ei velit detraxit</li>
                    </ul>
                    <a class="button" href="">Inregistrare</a>
                </div>
            </div>
        </div>
    </div>
</div>
