<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('Ofertele mele') ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <li>
                <strong><?php echo $this->__('Oferte active') ?></strong>
                <ul>
                    <li>Oferta 1</li>
                    <li>Oferta 2</li>
                </ul>
            </li>
            
            <li class="last">
                <strong><?php echo $this->__('Oferte inactive') ?></strong>
                <ul>
                    <li>Oferta 3</li>
                    <li>Oferta 4</li>
                </ul>
            </li>
        </ul>
    </div>
</div>
